### ISSUE TITLE
Update Repo

### ISSUE THREAD

**Issue by mlhess** [tsugiproject/tsugi-web#1]
# Motivation
In looking at the the https://tsugi.org/ website, I noticed that this repo is not up to date with the deployed version. There are some accessibility issues that I would like to fix. 

# Remaining tasks
Please keep this repo current with the deployed site so pull requests can be issued.

# API changes
none

**Comment by csev** [comment]
This is an old obsolete repo - the latest repo (as good as it is) is here

https://github.com/tsugiproject/tsugi-org

PR's welcome.
